[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[[bin]]
name = "obkrnl"
path = "src/main.rs"

[dependencies]
bitflags = "2.1"
byteorder = "1.4"
clap = { version = "4.1", features = ["derive"] }
directories = "5.0.1"
elf = { path = "../elf" }
iced-x86 = { version = "1.18", features = ["code_asm"] }
kernel-macros = { path = "../kernel-macros" }
libc = "0.2"
llvm-sys = { version = "160.0.2", features = ["strict-versioning"] }
log = "0.4.19"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
simplelog = "0.12.1"
termcolor = "1.1.*"
thiserror = "1.0"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.48", features = ["Win32_Foundation", "Win32_System_Diagnostics_Debug", "Win32_System_Memory", "Win32_System_SystemInformation"] }
